# Use something that's not 'ruby' so we don't set up things like
# RVM/bundler/ruby and whatnot. Right now 'rust' isn't a language on
# travis and it treats unknown languages as ruby
language: c

install:
  - curl -s http://www.rust-lang.org/rustup.sh | sudo sh
script:
  - /usr/local/bin/cargo build --verbose
  - /usr/local/bin/cargo test --verbose
