# Use something that's not 'ruby' so we don't set up things like
# RVM/bundler/ruby and whatnot. Right now 'rust' isn't a language on
# travis and it treats unknown languages as ruby
language: c

before_install:
  - yes | sudo add-apt-repository ppa:cmrx64/cargo
  - sudo apt-get update
install:
  - curl -s http://www.rust-lang.org/rustup.sh | sudo sh
  - sudo apt-get install cargo
script:
  - cargo build --verbose
  - cargo test --verbose
