# Use something that's not 'ruby' so we don't set up things like
# RVM/bundler/ruby and whatnot. Right now 'rust' isn't a language on
# travis and it treats unknown languages as ruby
language: c

install:
  - wget http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz -O - | sudo tar zxf - --strip-components 1 -C /usr/local
  - yes | sudo add-apt-repository ppa:cmrx64/cargo
  - sudo apt-get update
  - sudo apt-get install cargo
script:
  - cargo build
  - cargo test
