language: rust
script:
  - |
    cargo build &&
    cargo test &&
    echo "Testing README" &&
    rustdoc --test README.md -L dependency=./target/debug/deps --extern mustache=./target/debug/libmustache.rlib
