[package]
name = "mustache"
description = "Rust implementation of Mustache"
repository = "https://github.com/nickel-org/rust-mustache"
version = "0.6.2"
authors = ["erick.tryzelaar@gmail.com"]
license = "MIT/Apache-2.0"

[features]
unstable = []

[dependencies]
rustc-serialize = "*"
log = "*"

[dev-dependencies]
tempdir = "*"
